# Generated by Django 5.1.3 on 2024-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=150)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_apellido', models.CharField(max_length=150)),
            ],
        ),
    ]
